### ISSUE TITLE
RoVer sometimes gives old names

### ISSUE THREAD

**Issue by Blooochamp** [evaera/RoVer#137]
https://verify.eryn.io/api/user/252216078359330817

My new name is Bluwhy however, over here it says BlueChampion90

This might be just the API, since RoVer mostly does it correctly

A solution could be updating the web API when RoVer is too

**Comment by evaera** [comment]
Hi,

The verify.eryn.io API returns the username and user ID that was used at the time of verification. There is no guarantee that the given username is up-to-date. We do one initial call to resolve the user ID into a username, and then store that in our system.

When RoVer fetches the user information from the API, only the user ID portion is used. RoVer then issues a separate request to api.roblox.com to resolve the user ID into the current username for that user. If api.roblox.com is unavailable (which, due to Roblox maintenance, sometimes it is), then the username from verify.eryn.io is used as a fallback.

If you are writing custom software to integrate with verify.eryn.io, I suggest that you follow a similar paradigm.

Thanks
