### ISSUE TITLE
Can't unverify

### ISSUE THREAD

**Issue by genericusernameidonotcareabout** [evaera/RoVer#143]
The "unverify" option is entirely useless and doesn't do anything whatsoever. No matter how many times you use it, with or without the username you're verified as typed in, it keeps you verified. Even if you join a new server the bot still knows who you are.

**Comment by evaera** [comment]
Hi there, unfortunately due to a temporary technical limitation the "unverify" feature is no longer functional. You can, however, overwrite your verification with a new Roblox account. This is just a growing pain due to RoVer's quick growth and I had to apply an emergency patch to the verification registry for performance reasons but it has the side effect of no longer allowing verifications to be deleted, only overridden.

This will be fixed eventually, but for right now the only option is to just verify with a different account. Sorry for any inconvenience this may have caused you.
