### ISSUE TITLE
Huge servers have settings corrupted on a regular basis (approx. every 2 months)

### ISSUE THREAD

**Issue by evaera** [evaera/RoVer#153]
It seems RoVer will corrupt server settings if a settings read happens at the same instant that settings are written. Only really noticeable in big servers, because this is a really rare occurrence. Need to investigate this more and figure out where exactly the source of this is from. 

Right now, this happens on RoVer's biggest server (Jailbreak) about every 2 months, and it has over 100,000 members, so this is quite hard to reproduce.

**Comment by devSparkle** [comment]
I think we should start from the basic idea of _what is changing_:

- What happens after ~2 months.
- What happens gradually since a bot is configured?

That being said, here are a few suggestions of my own of things which could be causing the issue:

- Are there too many users in cache?
- Are there too many events being triggered, and could this be disregarded as the amount of events does not increase unless the amount of users increase?
- Are there too many role checks per user?

If this consistently happens every two months, then we could reasonably conclude that there must be a _buildup_ for this to happen, and as such must be an issue triggered by an increasing amount of data being handled / stored with time.

**Comment by Tigerism** [comment]
i mean, what can you expect from json files to store data
double writes happening at the same time = corrupted
read and write happening at the same time = corrupted

json is not a database

**Comment by wr1ght** [comment]
This issue is ridiculous, anyone can figure out the root cause.

Refer to the issue I opened here: https://github.com/evaera/RoVer/issues/154

**Comment by evaera** [comment]
Yeah, totally agree with you. RoVer is a small project I started in my free time that's just grown like crazy. I am fully aware that the current situation we have is not feasible, and I've commented on that in announcements multiple times. However, due to other obligations in my professional life, I'm unable to dedicate a large amount of time to RoVer.

I know the steps that need to be taken to build a scalable solution, and I've started down that path already. I'm starting with updating the verification website (verify.eryn.io), and as RoVer is open source, anyone is free to chip in and assist. Otherwise, please be patient, as I am doing my best juggling a ton of projects.

Thanks

**Comment by Blackcatmaxy** [comment]
I know you said you've been busy but this is not fixed at all, I'm a moderator in two major discord (ber games and Vesteria) and we get pinged somewhere along the lines of once a week for the settings being reset and all the bindings disappearing

**Comment by ImmortalSlayer** [comment]
We fix the binding issue in vCaffy's Games by simply rebinding the binded roles. It's not a permanent solution but it does work quite well.
