### ISSUE TITLE
Self-Hosting

### ISSUE THREAD

**Issue by roblox-interpol** [evaera/RoVer#247]
Is it possible to Self-Host RoVer on glitch? I’ve been doing some research but I am unsure if it is possible or not.

**Comment by coexperience** [comment]
Glitch is designed for web apps, not Discord bots.

With that said, it is possible; although you’ll need to use a service that regularly pings your project to keep the bot online.

Although I would suggest against using Glitch for *any* production projects.

**Comment by Sup-Sup123** [comment]
Actually glitch can be used to self-host your discord bot. But you need to
use something to ping the code such as uptime robot to ping the code every
few minutes. I know it works because that's how I self-host my discord
bots. If you need more help with glitch.com dm me on discord. Zach
Ikenberry#0548

**Comment by moo1210** [comment]
I mean a $10/month (or $8 a month annually)  plan that I don't recommend will enable your bot to not go to sleep,  It would be a better idea to find a better service.

**Comment by Sup-Sup123** [comment]
Glitch.com is guaranteed to work because it's free even though you need to
use uptimerobot.com to ping the code every few minutes.
