### ISSUE TITLE
Deal with nicknames being longer than 32 characters

### ISSUE THREAD

**Issue by MichaelFedora** [evaera/RoVer#56]
I know it's a duplicate of #32 , #42 , and #24 , but none of these have solutions that are implementable by us on the server side.

Lots of the
> @\<User>, RoVer couldn't modify the member in this server. Either the bot doesn't have permission or the target user cannot be modified by the bot (such as higher rank in the server).

messages, however these people trying to verify have none or close to no ranks whatsoever, all of which would be lower than the bot anyways. It seems a little random, though I think most of the ones that are erroring are people that have already been verified, it's just the bot not being able to assign the role in this particular server.

~~Any ideas?~~

Issue was that the nickname format (`%DISCORDNAME% - (%USERNAME%)`)was too long, so it was crossing the 32 character limit.

**Comment by suufi** [comment]
Discord tag?

**Comment by PhoenixShay** [comment]
Please post a link to your discord server -- be careful if someone says they're there to help, only trust Shayne#2226 and eryn#4756

**Comment by MichaelFedora** [comment]
Thanks @PhoenixShay . Invite is [here](https://discord.gg/2gGmfS), you can PM me once your in.

**Comment by PhoenixShay** [comment]
No, we don't currently have a support discord, just Github issues.

**Comment by evaera** [comment]
This is caused by the nickname format making usernames be longer than 32 characters. This is never an issue without a custom nickname format, since Roblox nicknames are limited to less than that. 

Thoughts:
1) Could truncate the string so it is always 32 characters or less
2) Could also "smart" truncate it, meaning to dynamically truncate the replacement text starting from the rightmost symbol until the entire nickname is of appropriate length, e.g.
```
%USERNAME% = evaerea
%DISCORDNAME% = THISISASUPERDUPERLONGSTRINGTHATWILLBREAKIT
Format = "%USERNAME - %(DISCORDNAME%)"
Nickname = "evaera - (THISISASUPERDUP)"
```
I think method 2 is nice, but it's probably a bit too complicated to explain. It might just be more user friendly to use the first method and let the server owners realize that's the problem.. 🤔

**Comment by MichaelFedora** [comment]
I agree with method 1, as it would be much similar to have the bot truncate and then start throwing warnings into the chat when a person is verified if their nickname is too long.

Method 2, while nice, could be a little complicated but it is still possible (and rather clean). Capture the length of the preset, insert the first variable, capture length again, insert whatever you can regarding the second variable, etc etc.
