### ISSUE TITLE
Feature Request: !update @everyone

### ISSUE THREAD

**Issue by MichaelFedora** [evaera/RoVer#58]
A very useful feature for large servers would be an `!update @everyone` (alternatively, `!update everyone`, `!update all`) to update every user to the new verified and unverified roles, as well as updating their nickname to the correct format. It's nigh impossible to go through every single user on a large server and `!update` them manually.

**Comment by PhoenixShay** [comment]
People are automatically updated after chatting in a channel RoVer can see

**Comment by Kiansjet** [comment]
That's pretty resource intensive, updating a users username and role by contacting roblox every time a message is sent by a verified user

**Comment by evaera** [comment]
@Kiansjet  That's not how it works. It's cached in memory.

**Comment by evaera** [comment]
There are some big challenges with this.

- RoVer restarts on a regular interval. If RoVer restarts in the middle of updating everyone, the progress will be lost unless it's saved. Right now we don't have any good way to do this, since RoVer doesn't save any state information at all (only configuration, which is different from this).
- RoVer averages about 166 requests per minute (2.7 per second) so adding this to update every single member would add a lot of strain. Perhaps could get around this by using a prioritized queue. I wouldn't want the queue to go one at a time though, because that would be too slow and induce idle time while we wait for requests to come back. At the same time, we can't do too many at once because we will likely hit some sort of pending request limit on the APIs we access (almost all of them on Roblox's servers, some unofficial APIs) and they'll think we're trying to attack them (which, even if our intentions are good, sending that many requests at once would be an attack regardless of the intent).
  - By a prioritized queue, I mean we have two queues wherein the system runs a loop that pulls the first few pending verifications off the front of the first queue, and if the first queue is empty, then go to the second queue. When someone joins a server or runs !verify, we add them to the front of the first queue, so they will always get verified before we go back to the second queue for lower-priority verifications.
- Even if we did a queue, that brings back the same problem as before with restarts clearing it. On the other hand, if we save the queue, then the queue could get so large for really big servers (or people being abusive with it) that it could take hours or actual days before a server's full update actually starts going. Not ideal either. Verifications can take anywhere from 1 to 5 seconds on average but can even get into the 20 second area depending on group rank bindings.

**Comment by evaera** [comment]
Going to close this for now, as I don't think this will work. Best solution is to just make a channel for people to send a message in to update their roles.
