### ISSUE TITLE
RoVer allows verifying multiple unique Discord's to one ROBLOX account

### ISSUE THREAD

**Issue by DBReinitialized** [evaera/RoVer#90]
I've recently discovered a rather nasty issue with RoVer as it allows for multiple Discord's to verify under one ROBLOX account. This is rather problematic as it opens users to potential risk of identity thefts with old/unused accounts which they cannot unlink, or a third party intentionally verifying another Discord account so RoVer will treat them as verified.

**Why I'm filing this as an issue?**
In Bleu Pigs (A community I run), my server bot PigBot identified two users as the same ROBLOX user. I even checked the RoVer API itself just to be sure, and these two Discord IDs are linked to the same account:
189166752649838593
217015101553770497
This lead to confusion as not only did people not realize there was a fake, but the person was intentionally acting to be said person they were not. I use RoVer as a method to ensure the person who is joining is who they claim to be, and so members of my community can trust they are who they claim and no one else. If RoVer can't be trusted, my community can't be sure the person is who they claim, which can cause either confusion or lead to malicious intent.

**How to reproduce:**
- Sign into Discord, perform verification on ROBLOX account
- Sign into another Discord account, perform verification on same ROBLOX account
- Check API, it'll show both are verified.

**Comment by evaera** [comment]
Hi. The verification registry project is actually entirely separate from RoVer, so this isn't technically a problem with RoVer. Not trying to be smart with you since I know there is no official way to report bugs with verify.eryn.io, just wanted to point that out. 

The behavior you're referring to is not necessarily _intended_, but this doesn't come as a surprise to me either. I've encountered cases where people actually use multiple Discord accounts and want to be verified on the same account, so I figured that no harm would come of it. This is definitely a sticky situation, though, because in the case of an account being compromised like in this case, there's no way the user can unverify that account without knowing the Discord account information.

I have plans to completely rewrite the verify.eryn.io project, and when that's done there will be a more long-term solution to this problem.

For now, if you could contact me on Discord, I will manually remove the compromised account. You can join the RoVer official server to message me, https://discord.gg/rgKt6Mw
